åç§°ï¼šGitHub Actions æ¼”ç¤º
è¿è¡Œåç§°ï¼š${{ github.actor }} æ­£åœ¨æµ‹è¯• GitHub Actions ğŸš€ 
ï¼š[push] 
jobsï¼š
  Explore-GitHub-Actionsï¼š
    runs-onï¼šubuntu-latest
    æ­¥éª¤ï¼š
      - runï¼šecho " ğŸ‰ è¯¥ä½œä¸šç”± ${{ github.event_name }} äº‹ä»¶è‡ªåŠ¨è§¦å‘ã€‚â€ 
      - run: echo "ğŸ§ æ­¤ä½œä¸šç°åœ¨æ­£åœ¨ GitHub æ‰˜ç®¡çš„ ${{ runner.os }} æœåŠ¡å™¨ä¸Šè¿è¡Œï¼" 
      - run: echo "ğŸ” æ‚¨çš„åˆ†æ”¯åç§°æ˜¯ ${{ github.ref }}ï¼Œæ‚¨çš„å­˜å‚¨åº“æ˜¯ ${{ github.repository }}ã€‚" 
      - åç§°ï¼šæŸ¥çœ‹å­˜å‚¨åº“ä»£ç 
        ä½¿ç”¨ï¼šactions/checkout@v4 
      - è¿è¡Œï¼šechoâ€œğŸ’¡ ${{ github.repository }} å­˜å‚¨åº“å·²å…‹éš†åˆ°è¿è¡Œç¨‹åºã€‚â€ 
      - run: echo "ğŸ–¥ï¸ å·¥ä½œæµç¨‹ç°åœ¨å·²å‡†å¤‡å¥½åœ¨è¿è¡Œå™¨ä¸Šæµ‹è¯•æ‚¨çš„ä»£ç ã€‚" 
      - åç§°ï¼šåˆ—å‡ºå­˜å‚¨åº“ä¸­çš„æ–‡ä»¶
        è¿è¡Œï¼š | 
          ls ${{ github.workspace }} 
      - è¿è¡Œï¼š echo "ğŸ æ­¤ä½œä¸šçš„çŠ¶æ€æ˜¯ ${{ job.status }}ã€‚"
